import {test} from 'node:test';
import assert from 'node:assert/strict';
import {testD1} from './helpers/cloudflare-d1.mjs';
import {builderRpc,collectionCapacity} from '../cloudflare/collection-builder-v235.mjs';
const actor={id:'owner'};
function fixture(t,n=0){const db=testD1();t.after(()=>db.close());db.sqlite.exec(`INSERT INTO profiles(id,display_name) VALUES ('owner','所有者'),('viewer','閲覧者'),('editor','編集者');INSERT INTO collections(id,owner_id,title,share_slug,book_tone) VALUES ('c','owner','テスト問題集','book','teal');INSERT INTO collection_members(collection_id,user_id,role) VALUES ('c','editor','editor'),('c','viewer','viewer');`);for(let i=1;i<=n;i++)db.sqlite.prepare(`INSERT INTO questions(id,collection_id,created_by,legacy_key,sort_order,source_report_id,payload,title) VALUES (?,'c','owner',?,?,?,?,?)`).run(`q${i}`,`legacy${i}`,i,`report${i}`,JSON.stringify({number:i,id:`q${i}`,answer:'fixture'}),`問題${i}`);return {db,actor};}
const question=i=>({p_share_slug:'book',p_title:'生成候補',p_payload:{id:`new${i}`,handBeforeDraw:['man1','man2','man3','man4','man5','man6','man7','man8','man9','pin1','pin2','pin3','ji1'],draw:'ji1',actualDiscard:'ji1',melds:[]},p_source_kind:'naga_scene',p_source_report_id:`new${i}`,p_scene_tw:0,p_scene_ts:0,p_scene_tv:i});
test('create with chosen color is private, idempotent and cannot impersonate',async t=>{const ctx=fixture(t);const input={p_title:'新しい本',p_book_tone:'plum',p_request_id:crypto.randomUUID(),owner_id:'viewer'};const a=await builderRpc('create_collection',input,ctx),b=await builderRpc('create_collection',input,ctx);assert.equal(a.id,b.id);assert.equal(a.owner_id,'owner');assert.equal(a.visibility,'private');assert.equal(a.book_tone,'plum');await assert.rejects(builderRpc('create_collection',{...input,p_book_tone:'red;url(x)'},ctx));});
test('195 preview, next-volume inheritance and replay preserve the original questions',async t=>{const ctx=fixture(t,195);const cap=await collectionCapacity({p_share_slug:'book'},ctx);assert.equal(cap.near_capacity,true);assert.equal(cap.remaining,5);const a=await builderRpc('create_collection_volume',{p_share_slug:'book',p_volume_number:2},ctx);const b=await builderRpc('create_collection_volume',{p_share_slug:'book',p_volume_number:2},ctx);assert.equal(a.id,b.id);assert.equal(a.book_tone,'teal');assert.equal(a.visibility,'private');assert.equal(ctx.db.sqlite.prepare("SELECT COUNT(*) n FROM questions WHERE collection_id='c'").get().n,195);assert.equal(ctx.db.sqlite.prepare('SELECT role FROM collection_members WHERE collection_id=? AND user_id=?').get(a.id,'editor').role,'editor');assert.equal(a.title,'テスト問題集 第2巻');});
test('194 has no warning and cannot create an early extra volume',async t=>{const ctx=fixture(t,194);assert.equal((await collectionCapacity({p_share_slug:'book'},ctx)).near_capacity,false);await assert.rejects(builderRpc('create_collection_volume',{p_share_slug:'book'},ctx),e=>e.code==='volume_not_ready');});
test('at 199 simultaneous inserts stop at 200 and duplication is idempotent',async t=>{const ctx=fixture(t,199);const result=await Promise.all([builderRpc('create_shared_question',question(1),ctx),builderRpc('create_shared_question',question(2),ctx)]);assert.equal(result.filter(x=>x.question_id).length,1);assert.equal(result.filter(x=>x.capacity_reached).length,1);assert.equal(ctx.db.sqlite.prepare('SELECT COUNT(*) n FROM questions').get().n,200);const duplicate=await builderRpc('create_shared_question',question(result[0].question_id?1:2),ctx);assert.equal(duplicate.already_exists,true);});
test('DB also rejects direct insert and restore above cap',async t=>{const ctx=fixture(t,200);assert.throws(()=>ctx.db.sqlite.exec(`INSERT INTO questions(id,collection_id,created_by,source_report_id) VALUES ('extra','c','owner','extra')`),/collection_capacity_reached/);ctx.db.sqlite.exec(`INSERT INTO questions(id,collection_id,created_by,source_report_id,deleted_at) VALUES ('old','c','owner','old','2026-01-01')`);assert.throws(()=>ctx.db.sqlite.exec("UPDATE questions SET deleted_at=NULL WHERE id='old'"),/collection_capacity_reached/);});
test('editor may add but cannot recolor or create volumes, viewer cannot write',async t=>{const ctx=fixture(t,195);for(const name of ['create_collection_volume','set_collection_book_tone'])await assert.rejects(builderRpc(name,{p_share_slug:'book',p_book_tone:'navy'},{...ctx,actor:{id:'editor'}}),e=>e.status===403);await assert.rejects(builderRpc('create_shared_question',question(1),{...ctx,actor:{id:'viewer'}}),e=>e.status===403);assert.ok((await builderRpc('create_shared_question',question(1),{...ctx,actor:{id:'editor'}})).question_id);});
test('guard and embedded image uploads remain blocked',async t=>{const ctx=fixture(t);ctx.db.sqlite.exec("INSERT INTO private_ops_capacity_control(singleton,armed,blocked,checked_at) VALUES(1,1,1,'2026-09-12')");await assert.rejects(builderRpc('create_shared_question',question(1),ctx),e=>e.code==='heavy_operations_paused');ctx.db.sqlite.exec('UPDATE private_ops_capacity_control SET armed=0');await assert.rejects(builderRpc('create_shared_question',{...question(1),p_payload:{id:'a',image:'data:image/png;base64,a'}},ctx),e=>e.code==='question_image_upload_required');});
test('import requires source access and uses server-assigned number',async t=>{const ctx=fixture(t,1);const book=await builderRpc('create_collection',{p_title:'保存先',p_request_id:crypto.randomUUID()},ctx);const a=await builderRpc('import_shared_question',{p_source_question_id:'q1',p_target_share_slug:book.share_slug},ctx);assert.equal(a.question_number,1);const b=await builderRpc('import_shared_question',{p_source_question_id:'q1',p_target_share_slug:book.share_slug},ctx);assert.equal(b.already_exists,true);await assert.rejects(builderRpc('import_shared_question',{p_source_question_id:'q1',p_target_share_slug:book.share_slug},{...ctx,actor:{id:'outsider'}}),e=>e.status===404);});
test('generated broken titles are repaired on add, custom numbered titles stay intact',async t=>{const ctx=fixture(t);const a=await builderRpc('create_shared_question',{...question(1),p_title:'問題-Infinity'},ctx);assert.equal(ctx.db.sqlite.prepare('SELECT title FROM questions WHERE id=?').get(a.question_id).title,'問題1');const b=await builderRpc('create_shared_question',{...question(2),p_title:'問題5 の手筋'},ctx);assert.equal(ctx.db.sqlite.prepare('SELECT title FROM questions WHERE id=?').get(b.question_id).title,'問題5 の手筋');});
test('concurrent requests for the same scene with different payload IDs reuse the row',async t=>{const ctx=fixture(t);const a=question(1),b={...a,p_payload:{...a.p_payload,id:'another-client-id'}};const result=await Promise.all([builderRpc('create_shared_question',a,ctx),builderRpc('create_shared_question',b,ctx)]);assert.equal(result[0].question_id,result[1].question_id);assert.equal(ctx.db.sqlite.prepare('SELECT COUNT(*) n FROM questions').get().n,1);});
