import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const indexUrl = new URL("../public/index.html", import.meta.url);

test("renders the v87 scene and half-game generator controls", async () => {
  const html = await readFile(indexUrl, "utf8");
  assert.match(html, /const APP_VERSION = 95/);
  assert.match(html, /data-range-session="all">この範囲を10問解く/);
  assert.doesNotMatch(html, /data-range-session="unanswered">未回答を10問解く/);
  assert.match(html, /range: "この範囲の10問"/);
  assert.match(html, /"range-unanswered": "未回答の10問"/);
  assert.match(html, /id="menuOrderSelect"/);
  assert.match(html, /let menuOrderV92 = "sequential"/);
  assert.match(html, /menuOrderV92 === "reverse"/);
  assert.match(html, /menuOrderV92 === "random"/);
  assert.match(html, /function answerCountV93\(question\)/);
  assert.match(html, /function randomizeQuestionsByAnswerCountV93\(items\)/);
  assert.doesNotMatch(html, /candidates\.filter\(question => !latestAnswerV44\(question\)\)/);
  assert.match(html, /\[\.\.\.APP_ANNOUNCEMENTS_V66\]\s*\.sort\(\(left, right\) => right\.version - left\.version\)/);
  assert.match(html, /data-menu-view="settings"/);
  assert.match(html, /id="displayNameForm"/);
  assert.match(html, /displayNameLengthV67/);
  assert.match(html, /id="announcementButton"/);
  assert.match(html, /id="commentNotificationsButton"/);
  assert.match(html, /function startCommentNotificationPollingV65/);
  assert.match(html, /function refreshSharedQuestionNotificationsV66/);
  assert.match(html, /QUESTION_NOTICE_STORAGE_KEY_V66/);
  assert.match(html, /function renderCommunityNotificationListV66/);
  assert.match(html, /data-comment-action="edit"/);
  assert.match(html, /data-comment-action="delete"/);
  assert.match(html, /function beginCommentEditV75/);
  assert.match(html, /function deleteCommentV75/);
  assert.match(html, /data-community-notification-kind="question"/);
  assert.match(html, /data-menu-question-notification/);
  assert.match(html, /data-menu-range-notification/);
  assert.doesNotMatch(html, /data-menu-view="session"/);
  assert.match(html, /grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)/);
  assert.doesNotMatch(html, /id="menuViewNote"/);
  assert.doesNotMatch(html, /解きたい局面を選んでください/);
  assert.match(html, /function menuRowStatusV63/);
  assert.match(html, /function menuScoreMarkClassV63/);
  assert.match(html, /function menuTrashIconV63/);
  assert.match(html, /class="menu-sidebar"/);
  assert.match(html, /id="menuListHeader"/);
  assert.match(html, /class="menu-list-header-group"><span>問題<\/span>/);
  assert.match(html, /\.menu-list-header \{[\s\S]*?grid-template-columns: 1fr;[\s\S]*?gap: 0;/);
  assert.match(html, /\.menu-grid \{[\s\S]*?grid-template-columns: 1fr;[\s\S]*?gap: 0;/);
  assert.match(html, /function normalizeQuestionTitleV79\(title, number\)/);
  assert.match(html, /title: `問題\$\{nextNumber\}`/);
  assert.match(html, /normalizeQuestionTitlesV79\(\);/);
  assert.match(html, /function menuFilterActiveV80\(\)/);
  assert.match(html, /function menuFilteredQuestionsV80\(\)/);
  assert.match(html, /function hydrateRemoteAnswerHistoryV81\(\)/);
  assert.match(html, /loadMyAttempts\(500\)/);
  assert.match(html, /const orderedCandidates = menuOrderV92 === "reverse"/);
  assert.match(html, /menuOrderV92 === "random"/);
  assert.match(html, /randomizeQuestionsByAnswerCountV93\(candidates\)/);
  assert.match(html, /function nextFilteredQuestionV87\(\)/);
  assert.match(html, /menu-card-latest/);
  assert.match(html, /data-menu-action="favorite"/);
  assert.match(html, /data-menu-action="trash"/);
  assert.match(html, /id="menuRangeTabs"/);
  assert.match(html, /id="menuRangeHeading">問題範囲/);
  assert.match(html, /id="menuTypeFilters"/);
  assert.match(html, /data-menu-type="call"/);
  assert.match(html, /id="menuAdvancedToggle"/);
  assert.match(html, /id="menuAdvancedFilters"/);
  assert.match(html, /回答状態（複数選択可）/);
  assert.doesNotMatch(html, /data-menu-status="due"/);
  assert.match(html, /data-menu-status="unanswered"/);
  assert.match(html, /data-menu-status="weak"/);
  assert.match(html, /data-menu-status="mastered"/);
  assert.doesNotMatch(html, /id="menuStatusFilter"/);
  assert.match(html, /function renderMenuTypeFiltersV83\(\)/);
  assert.doesNotMatch(html, /id="menuSearch"/);
  assert.doesNotMatch(html, /id="menuTypeFilter"/);
  assert.match(html, /function canViewStudentDashboardV84\(\)/);
  assert.match(html, /studentNav\.hidden = !canViewStudentDashboardV84\(\)/);
  assert.match(html, /所有者専用の生徒進捗画面を追加しました/);
  assert.match(html, /function menuRangeOptionsV60\(\)/);
  assert.match(html, /sourceQuestions\.filter\(menuRangeMatchesV60\)/);
  assert.match(html, /class="menu-brand-title">My問題集<\/span><span class="menu-brand-actions">/);
  assert.match(html, /getElementById\("menuVersion"\)\.textContent = APP_VERSION/);
  assert.match(html, /width: min\(850px, 100%\)/);
  assert.match(html, /aspect-ratio: 14 \/ 13/);
  assert.match(html, /name="generatorMode"/);
  assert.match(html, /value="scene"/);
  assert.match(html, /class="call-target-tile"/);
  assert.match(html, /class="riichi-layer"/);
  assert.match(html, /sceneFrameV16\.querySelector\("\.call-controls"\)\?\.remove\(\)/);
  assert.match(html, /sceneFrameV16\.querySelector\("\.riichi-layer"\)\?\.remove\(\)/);
  assert.match(html, /sceneFrameV16\.classList\.toggle\("is-call-decision", SCENE\.decisionType === "call"\)/);
  assert.match(html, /sceneFrameV16\.insertAdjacentHTML\("beforeend", `<div class="call-controls"/);
  assert.match(html, /sceneFrameV16\.insertAdjacentHTML\("beforeend", `<div class="riichi-layer"/);
  assert.doesNotMatch(html, /getElementById\("handLayer"\)\.insertAdjacentHTML\("beforeend", `<div class="call-controls"/);
  assert.match(html, /当時の選択（鳴き）/);
  assert.match(html, /value="match"/);
  assert.match(html, /id="generatorSeat"/);
  assert.match(html, /player_info\?\.name/);
  assert.match(html, /id="generatorThreshold"[^>]+min="0\.1"[^>]+max="50"/);
  assert.match(html, /id="generatorDecisionType"/);
  assert.match(html, /value="discard"/);
  assert.match(html, /value="call"/);
  assert.match(html, /value="reach"/);
  assert.match(html, /id="generatorModelMode"/);
  assert.match(html, /value="all">全モデルで悪手/);
  assert.match(html, /id="generatorMaxCandidates"[^>]+max="500"/);
  assert.match(html, /局面URLではURLにtsとtvの両方が必要です/);
  assert.match(html, /ts: null, tv: null/);
  assert.match(html, /extractBadMoves\(report, seat, \{ \.\.\.extraction, reportId: spec\.reportId \}\)/);
  assert.match(html, /captureGeneratorCandidateV51/);
  assert.match(html, /data-generator-capture/);
  assert.match(html, /captureNagaScene/);
  assert.match(html, /問題候補が完成しました/);
  assert.doesNotMatch(html, /id="surroundingsToggle"/);
  assert.doesNotMatch(html, /SCENE_IMAGES/);
  assert.doesNotMatch(html, /images: \{ off: candidate\._imageData, open: candidate\._imageData \}/);
  assert.match(html, /data-comment-format="bold"/);
  assert.match(html, /data-comment-format="spoiler"/);
  assert.match(html, /id="commentColorSelect"/);
  assert.match(html, /id="commentSizeSelect"/);
  assert.match(html, /id="commentDropzone"/);
  assert.match(html, /function addCommentFilesV68/);
  assert.match(html, /id="nextQuestionButton"[^>]*>次の問題へ<\/button>/);
  assert.match(html, /id="nextQuestionBottomButton"[^>]*>次の問題へ<\/button>/);
  assert.doesNotMatch(html, /id="resetButton"/);
  assert.match(html, /id="currentManageButton"[^>]*>整理<\/button>/);
  assert.match(html, /const nextTenAction = result\.mode === "range-unanswered" \? "range-unanswered" : "unanswered";/);
  assert.match(html, /const nextTenLabel = unansweredMode \? "次の10問へ" : "新しい10問";/);
  assert.match(html, /action === "unanswered"/);
});

test("renders NAGA-like inset probability bars with a dynamic judge highlight", async () => {
  const html = await readFile(indexUrl, "utf8");
  assert.match(html, /--nishiki: #9b78ff/);
  assert.match(html, /--hihikari: #f1c457/);
  assert.match(html, /--kagashi: #4aa8ff/);
  assert.match(html, /--omega: #f39a3f/);
  assert.match(html, /--gamma: #55d59b/);
  assert.match(html, /\.probability-stack \{[^}]*left: 2px;[^}]*width: calc\(100% - 4px\);[^}]*background: transparent/);
  assert.match(html, /\.probability-mini-track \{[^}]*flex: 1 1 0;/);
  assert.match(html, /\.probability-mini-fill \{[^}]*left: 50%;[^}]*width: 3px;[^}]*background: #68735b/);
  assert.match(html, /\.probability-mini-fill\.is-judge-model \{[^}]*width: 7px;/);
  assert.match(html, /\.probability-mini-fill\.is-judge-model \{[^}]*width: 7px;[^}]*background: var\(--nishiki\)/);
  assert.match(html, /data-bar-count="\$\{entries\.length\}"/);
  assert.match(html, /is-judge-model/);
  assert.match(html, /is-reference-model/);
  assert.doesNotMatch(html, /--bar-slot/);
});
