import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../public/generation-confirm-v241.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
test('save confirmation preserves local and shared impact warnings',()=>{assert.match(source,/この問題集の利用者に反映されます。/);assert.match(source,/この端末だけに保存されます。/);});
function fixture(){let onClose;const dialog={open:false,returnValue:'',addEventListener(type,cb,options){assert.equal(type,'close');assert.equal(options.once,true);onClose=cb;},showModal(){this.open=true;},close(value){this.open=false;this.returnValue=value;onClose();}};const description={textContent:''},window={};vm.runInNewContext(source,{window});return {dialog,description,api:window.NagaGenerationConfirmV241,document:{getElementById:id=>id==='generatorSaveDialogV241'?dialog:description}};}
test('saving needs a separate explicit accept and safely displays the exact destination and count',async()=>{const f=fixture();let settled=false;const result=f.api.ask(f.document,{label:'<private book>',kind:'shared'},1).then(v=>{settled=true;return v;});assert.equal(f.dialog.open,true);assert.equal(settled,false);assert.match(f.description.textContent,/<private book>.*1問/);f.dialog.close('add');assert.equal(await result,true);});
test('cancel, Escape, invalid count and a second concurrent prompt cannot save',async()=>{for(const value of ['cancel','']){const f=fixture(),pending=f.api.ask(f.document,{label:'Fixture',kind:'local'},1);assert.equal(await f.api.ask(f.document,{label:'Other',kind:'local'},1),false);f.dialog.close(value);assert.equal(await pending,false);}const f=fixture();assert.equal(await f.api.ask(f.document,{label:'Fixture'},0),false);assert.equal(f.dialog.open,false);});
test('both save paths retain confirmation and the dialog has a named cancel-first keyboard path',()=>{assert.match(html,/if \(!await window\.NagaGenerationConfirmV241\.ask\(document, destination, indexes.length\)\) return/);assert.match(html,/if \(!skipConfirm && !await window\.NagaGenerationConfirmV241\.ask\(document, destination, 1\)\) return false/);assert.match(html,/id="generatorSaveDialogV241" aria-labelledby="generatorSaveTitleV241" aria-describedby="generatorSaveDescriptionV241"/);assert.match(html,/value="cancel" autofocus>キャンセル/);assert.doesNotMatch(source,/innerHTML|fetch\(|NagaSupabase|localStorage|\.click\(/);});
