import test from 'node:test';
import assert from 'node:assert/strict';
import {testD1} from './helpers/cloudflare-d1.mjs';
import {imageUpload,questionMediaKeys} from '../cloudflare/media-write-v241.mjs';
import {createGenerationApi} from '../cloudflare/generation-api-v241.mjs';
import {requireGenerationCapacity,reserveUsage,reconcileMediaBudget} from '../cloudflare/generation-capacity-v241.mjs';
import {createCloudflareClient} from '../client/cloudflare-transport.mjs';
import {mediaRead} from '../cloudflare/media-read.mjs';
import {builderRpc} from '../cloudflare/collection-builder-v235.mjs';
import worker from '../cloudflare/worker.mjs';
import {sha256} from '../cloudflare/auth.mjs';
const origin='https://fixture.test',reportId='fixture_report_abcdefghijklmnop';
const png=new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,1,0,0,0,1]);
const owner={id:'owner'},viewer={id:'viewer'},outsider={id:'outsider'};
async function digest(bytes){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),n=>n.toString(16).padStart(2,'0')).join('');}
function r2(){const objects=new Map();let puts=0,gets=0;return {objects,get puts(){return puts;},get gets(){return gets;},async head(key){return objects.get(key)||null;},async get(key){gets++;return objects.get(key)||null;},async put(key,bytes,options){if(objects.has(key))return null;puts++;const object={key,size:bytes.length,body:bytes,...options,writeHttpMetadata(headers){headers.set('Content-Type',options.httpMetadata.contentType);}};objects.set(key,object);return object;},async list(){return {objects:[...objects.values()],truncated:false};}};}
function setup(t){const db=testD1({generation:true});t.after(()=>db.close());db.sqlite.exec(`INSERT INTO profiles(id) VALUES('owner'),('viewer'),('outsider');INSERT INTO auth_identities(user_id,discord_user_id) VALUES('owner','123456789012345678');INSERT INTO collections(id,owner_id,title,share_slug) VALUES('book','owner','Private test','test');INSERT INTO collection_members(collection_id,user_id,role) VALUES('book','viewer','viewer');`);db.sqlite.prepare('INSERT INTO private_media_budget(singleton,inventory_checked_at) VALUES(1,?)').run(new Date().toISOString());return {DB:db,APP_ORIGIN:origin,GENERATION_ENABLED:'true',UPLOADS_ENABLED:'true',MEDIA_LINKS_ENABLED:'true',BROWSER:{},IMAGES:r2(),ARCHIVES:r2()};}
async function uploadRequest(bytes=png,extra={}){return new Request(origin+'/v1/assets',{method:'POST',headers:{'Content-Type':'image/png','X-Asset-Bucket':'question-assets','X-Collection-Slug':'test','X-Asset-SHA256':await digest(bytes),...extra},body:bytes});}

test('report uses Workers-compatible manual redirects and optional caching cannot block generation',async t=>{
  const env=setup(t);let calls=0;
  const api=createGenerationApi({cache:{async match(){return null;},async put(){throw Error('fixture cache unavailable');}},fetchImpl:async(url,options)=>{calls++;assert.equal(options.redirect,'manual');return Response.json({pred:[]});}});
  assert.equal((await api('naga-report',{reportId},env,owner)).status,200);assert.equal(calls,1);
  const redirect=createGenerationApi({fetchImpl:async(url,options)=>{assert.equal(options.redirect,'manual');return new Response(null,{status:302,headers:{Location:'https://private.test'}});}});
  await assert.rejects(redirect('naga-report',{reportId},env,owner),e=>e.status===502);
});

test('image access and allowed re-import survive pausing new generation',async t=>{
  const env=setup(t),asset=await imageUpload(await uploadRequest(),env,owner),ctx={db:env.DB,actor:owner,origin};
  const source=await builderRpc('create_shared_question',{p_share_slug:'test',p_payload:{id:'paused-read-fixture',kind:'standard',title:'Fixture',image:asset.src},p_source_kind:'manual'},ctx);
  const target=await builderRpc('create_collection',{p_title:'Private copy fixture',p_request_id:crypto.randomUUID()},ctx);
  env.DB.sqlite.prepare("INSERT INTO collection_members(collection_id,user_id,role) VALUES(?,'outsider','viewer')").run(target.id);
  await builderRpc('import_shared_question',{p_source_question_id:source.question_id,p_target_share_slug:target.share_slug},ctx);
  env.GENERATION_ENABLED='false';env.UPLOADS_ENABLED='false';
  const result=await mediaRead(new Request(origin+'/v1/resolve',{method:'POST'}),env,{actor:outsider,body:{keys:[asset.bucket+'/'+asset.path]}});
  assert.equal(result.status,200);
  assert.deepEqual(await questionMediaKeys({image:asset.src},{db:env.DB,actor:outsider,origin}),[asset.bucket+'/'+asset.path]);
});
test('upload is private, hash-verified, independently counted, and idempotent under concurrency',async t=>{const env=setup(t);const a=await imageUpload(await uploadRequest(),env,owner),b=await imageUpload(await uploadRequest(),env,owner);assert.equal(a.path,b.path);assert.equal(env.IMAGES.puts,1);assert.equal(env.DB.sqlite.prepare('SELECT used_bytes FROM private_media_budget').get().used_bytes,png.length);assert.equal(env.DB.sqlite.prepare('SELECT state FROM media_assets').get().state,'ready');assert.match(a.src,/\/v1\/private\//);const resolve=await mediaRead(new Request(origin+'/v1/resolve',{method:'POST'}),env,{actor:owner,body:{keys:[a.bucket+'/'+a.path]}});const urls=(await resolve.json()).urls;const image=await mediaRead(new Request(urls[a.bucket+'/'+a.path]),env,{actor:viewer});assert.equal(image.status,200);assert.deepEqual(new Uint8Array(await image.arrayBuffer()),png);await assert.rejects(mediaRead(new Request(urls[a.bucket+'/'+a.path]),env,{actor:outsider}),e=>e.status===403);await assert.rejects(mediaRead(new Request(a.src),env,{actor:null}),e=>e.status===401);});
test('uploads reject other owners, wrong MIME/hash, unknown buckets and over-size bodies before R2 writes',async t=>{const env=setup(t);await assert.rejects(imageUpload(await uploadRequest(),env,viewer),e=>e.status===403);await assert.rejects(imageUpload(await uploadRequest(png,{'X-Asset-Bucket':'naga-question-assets'}),env,owner),e=>e.status===400);await assert.rejects(imageUpload(await uploadRequest(png,{'Content-Type':'image/webp'}),env,owner),e=>e.status===415);await assert.rejects(imageUpload(await uploadRequest(png,{'X-Asset-SHA256':'a'.repeat(64)}),env,owner),e=>e.status===422);await assert.rejects(imageUpload(await uploadRequest(png,{'Content-Length':'99999999'}),env,owner),e=>e.status===413);assert.equal(env.IMAGES.puts,0);});
test('pending reservations survive a failed PUT and a retry does not reserve twice',async t=>{const env=setup(t),put=env.IMAGES.put;env.IMAGES.put=async()=>{throw Error('fixture failure');};await assert.rejects(imageUpload(await uploadRequest(),env,owner));assert.equal(env.DB.sqlite.prepare('SELECT used_bytes FROM private_media_budget').get().used_bytes,png.length);env.IMAGES.put=put;await imageUpload(await uploadRequest(),env,owner);assert.equal(env.DB.sqlite.prepare('SELECT used_bytes FROM private_media_budget').get().used_bytes,png.length);});
test('capacity limits and stale/failed inventory fail closed without affecting reads',async t=>{const env=setup(t);env.DB.sqlite.exec('UPDATE private_media_budget SET limit_bytes=10');await assert.rejects(imageUpload(await uploadRequest(),env,owner),e=>e.status===507);assert.equal(env.IMAGES.puts,0);env.DB.sqlite.exec("UPDATE private_media_budget SET limit_bytes=8000000000,inventory_checked_at='2000-01-01'");env.ARCHIVES.list=async()=>{throw Error('not available');};await assert.rejects(requireGenerationCapacity(env),e=>e.status===503);assert.equal(env.DB.sqlite.prepare('SELECT inventory_error FROM private_media_budget').get().inventory_error,'metadata_inventory_failed');});
test('metadata refresh reads no image bodies and counts archives and pending reservations',async t=>{const env=setup(t);await imageUpload(await uploadRequest(),env,owner);await env.ARCHIVES.put('backup.gz',new Uint8Array(500),{});const result=await reconcileMediaBudget(env);assert.equal(result.imageBytes,png.length);assert.equal(result.archiveBytes,500);assert.equal(env.IMAGES.gets,0);assert.equal(env.ARCHIVES.gets,0);});
test('report retrieval is authenticated, allowlisted, bounded, and stores metadata only in D1',async t=>{const env=setup(t),calls=[];const api=createGenerationApi({fetchImpl:async(url)=>{calls.push(url);return Response.json({pred:[],fixture:'not a real mahjong report'});}});await assert.rejects(api('naga-report',{reportId},env,null),e=>e.status===401);await assert.rejects(api('naga-report',{reportId:'../../private'},env,owner),e=>e.status===400);const r=await api('naga-report',{reportId,targetPlayerSeat:0,sourceUrl:'https://evil.test'},env,owner),data=await r.json();assert.equal(data.report.fixture,'not a real mahjong report');assert.deepEqual(calls,['https://naga.dmv.nico/reports/'+reportId+'.json']);const job=env.DB.sqlite.prepare('SELECT * FROM generation_jobs').get();assert.equal(job.id,data.jobId);assert.equal(job.status,'completed');assert.equal(job.requested_by,'owner');assert.equal(Object.hasOwn(job,'report'),false);});
test('optional cache failures do not disable report retrieval',async t=>{const env=setup(t);let fetched=0;const api=createGenerationApi({cache:{match:async()=>{throw Error('cache unavailable');},put:async()=>{throw Error('cache unavailable');}},fetchImpl:async()=>{fetched++;return Response.json({pred:[]});}});const response=await api('naga-report',{reportId},env,owner);assert.deepEqual((await response.json()).report,{pred:[]});assert.equal(fetched,1);});
test('capture requires an owned completed job and uses canonical validated coordinates',async t=>{const env=setup(t);let captured;const api=createGenerationApi({fetchImpl:async()=>Response.json({pred:[]}),captureImpl:async(e,url)=>{captured=url;return png;}});const data=await(await api('naga-report',{reportId},env,owner)).json();const input={reportId,jobId:data.jobId,tw:1,ts:2,tv:3};await assert.rejects(api('naga-capture',input,env,outsider),e=>e.status===403);await assert.rejects(api('naga-capture',{...input,tw:null},env,owner),e=>e.status===400);const response=await api('naga-capture',input,env,owner);assert.equal(response.headers.get('Content-Type'),'image/png');assert.match(captured,/report_id=fixture_report_abcdefghijklmnop&tw=1&ts=2&tv=3$/);assert.ok(env.DB.sqlite.prepare("SELECT used FROM private_generation_usage WHERE kind='capture_seconds'").get().used>=2);});
test('capture and daily upload limits are atomic and do not retry',async t=>{const env=setup(t);await reserveUsage(env.DB,'capture_seconds','all',480,480);await assert.rejects(reserveUsage(env.DB,'capture_seconds','all',60,480),e=>e.status===429);let requests=0;const api=createGenerationApi({fetchImpl:async()=>{requests++;return new Response('',{status:429});}});await assert.rejects(api('naga-report',{reportId},env,owner),e=>e.status===429);assert.equal(requests,1);assert.equal(env.DB.sqlite.prepare('SELECT status FROM generation_jobs').get().status,'failed');});
test('private images cannot be attached by guessing keys; imported copies get their own authorized link',async t=>{const env=setup(t),asset=await imageUpload(await uploadRequest(),env,owner);await assert.rejects(questionMediaKeys({image:asset.src},{db:env.DB,actor:outsider,origin},'book'),e=>e.status===403);const ctx={db:env.DB,actor:owner,origin};const result=await builderRpc('create_shared_question',{p_share_slug:'test',p_payload:{id:'local-test',image:asset.src},p_source_kind:'manual'},ctx);assert.equal(env.DB.sqlite.prepare('SELECT question_id FROM media_question_links').get().question_id,result.question_id);await assert.rejects(questionMediaKeys({image:asset.src.replace(origin,'https://evil.test')},ctx,'book'),e=>e.status===422);});
test('cookie function transport supports JSON and image responses with CSRF and an allowlist',async()=>{const calls=[];const client=createCloudflareClient({document:{cookie:'__Host-minkiru_csrf=csrf'},fetchImpl:async(path,options)=>{calls.push({path,options});return path.endsWith('naga-capture')?new Response(png,{headers:{'Content-Type':'image/png'}}):Response.json({jobId:'fixture',report:{pred:[]}});}});const a=await client.functions.invoke('naga-report',{body:{reportId}});assert.equal(a.data.jobId,'fixture');const b=await client.functions.invoke('naga-capture',{body:{reportId}});assert.equal(b.data.type,'image/png');assert.equal(calls.length,2);assert.equal(calls[1].options.headers['X-Minkiru-CSRF'],'csrf');assert.equal(calls[1].options.credentials,'same-origin');assert.equal((await client.functions.invoke('arbitrary-admin')).error.status,403);assert.equal(calls.length,2);});
test('Worker upload route uses session, same-origin, CSRF and server flag before bytes',async t=>{const env=setup(t),token='a'.repeat(64),csrf='b'.repeat(64);Object.assign(env,{CUTOVER_READY:'true',DISCORD_CLIENT_ID:'123456789012345678',DISCORD_CLIENT_SECRET:'fixture-only'});env.DB.sqlite.prepare('INSERT INTO auth_sessions VALUES(?,?,?,?,?)').run(await sha256(token),'owner',await sha256(csrf),Math.floor(Date.now()/1000)+3600,0);const make=async wrong=>{const raw=await uploadRequest();const headers=new Headers(raw.headers);headers.set('Cookie','__Host-minkiru_session='+token);headers.set('Origin',origin);headers.set('X-Minkiru-CSRF',wrong?'wrong':csrf);return new Request(raw,{headers});};assert.equal((await worker.fetch(await uploadRequest(),env)).status,401);assert.equal((await worker.fetch(await make(true),env)).status,403);assert.equal((await worker.fetch(await make(false),env)).status,200);env.UPLOADS_ENABLED='false';assert.equal((await worker.fetch(await make(false),env)).status,503);const health=await(await worker.fetch(new Request(origin+'/health'),env)).json();assert.equal(health.bulkImport,false);assert.equal(health.bot,false);});
test('two simultaneous uploads cannot double-reserve or overwrite the same image',async t=>{const env=setup(t);const a=await uploadRequest(),b=await uploadRequest();const results=await Promise.all([imageUpload(a,env,owner),imageUpload(b,env,owner)]);assert.equal(results[0].path,results[1].path);assert.equal(env.IMAGES.puts,1);assert.equal(env.DB.sqlite.prepare('SELECT used_bytes FROM private_media_budget').get().used_bytes,png.length);});
test('an imported private image follows the copied question access, not the source book visibility',async t=>{const env=setup(t),asset=await imageUpload(await uploadRequest(),env,owner),ctx={db:env.DB,actor:owner,origin};const source=await builderRpc('create_shared_question',{p_share_slug:'test',p_payload:{id:'copy-fixture',image:asset.src},p_source_kind:'manual'},ctx);const target=await builderRpc('create_collection',{p_title:'Copy target',p_request_id:crypto.randomUUID()},ctx);env.DB.sqlite.prepare("INSERT INTO collection_members(collection_id,user_id,role) VALUES(?,'outsider','viewer')").run(target.id);const copy=await builderRpc('import_shared_question',{p_source_question_id:source.question_id,p_target_share_slug:target.share_slug},ctx);const resolved=await mediaRead(new Request(origin+'/v1/resolve',{method:'POST'}),env,{actor:outsider,body:{keys:[asset.bucket+'/'+asset.path]}});const url=(await resolved.json()).urls[asset.bucket+'/'+asset.path];assert.equal((await mediaRead(new Request(url),env,{actor:outsider})).status,200);env.DB.sqlite.prepare('UPDATE questions SET deleted_at=? WHERE id=?').run(new Date().toISOString(),copy.question_id);await assert.rejects(mediaRead(new Request(url),env,{actor:outsider}),e=>e.status===403);});
