import test from 'node:test';
import assert from 'node:assert/strict';
import {createOpsWorker,initialState,snapshot} from '../ops/worker.mjs';
import {DAY,HOUR} from '../ops/policy.mjs';
import {inventory,pruneSnapshots} from '../ops/collect.mjs';
class Bucket {
 constructor(){this.rows=new Map();this.seq=0;this.gets=0;this.deletes=[];}
 async get(key){this.gets++;const x=this.rows.get(key);return x?{...x,json:async()=>JSON.parse(x.body)}:null;}
 async put(key,body,options={}){const old=this.rows.get(key),c=options.onlyIf;if(c?.etagMatches&&old?.etag!==c.etagMatches||c?.etagDoesNotMatch==='*'&&old)return null;const x={key,body,etag:String(++this.seq),size:Buffer.byteLength(body),uploaded:new Date()};this.rows.set(key,x);return x;}
 async list({prefix='',cursor,limit=1000}={}){const rows=[...this.rows.values()].filter(x=>x.key.startsWith(prefix)).sort((a,b)=>a.key.localeCompare(b.key));const start=Number(cursor||0);return {objects:rows.slice(start,start+limit),truncated:rows.length>start+limit,cursor:String(start+limit)};}
 async delete(keys){for(const k of [keys].flat()){this.rows.delete(k);this.deletes.push(k);}}
}
const stamp=Date.parse('2026-09-07T12:00:00Z');
const egress={periodStart:'2026-09-06',periodEnd:'2026-10-06',confirmedAt:new Date(stamp).toISOString(),uncachedBytes:0,cachedBytes:0};
const source=value=>({value,checkedAt:new Date(stamp).toISOString(),lastSuccessAt:new Date(stamp).toISOString(),failures:0});
function healthy(){const state=initialState(stamp-2*DAY);state.enforcementApproved=true;state.successfulTicks=100;state.egress=egress;state.raw={minkiru:source({databaseBytes:100,tables:[],storage:[]}),ranking:source({databaseBytes:100,tables:[],storage:[]}),r2:source({bytes:100,imageBytes:90,imageCount:1,managementBytes:10,managementCount:1,activeBytes:90,activeCount:1,oldBytes:0,oldCount:0,unknownBytes:0,unknownCount:0}),cloudflare:source({workersRequests:1,classA:1,classB:1,day:'2026-09-07',month:'2026-09-01'}),egress:source({})};return state;}
const baseEnv=()=>({OPS_DATA:new Bucket(),IMAGES:new Bucket(),MINKIRU_URL:'https://main.supabase.co',RANKING_URL:'https://ranking.supabase.co',OPS_MONITOR_TOKEN:'test-token',CF_ACCOUNT_ID:'abc',CF_ANALYTICS_TOKEN:'test-analytics',DISCORD_BOT_TOKEN:'test-bot',OWNER_DISCORD_ID:'111111111111111111',COLLECTOR_ENABLED:'true',CONTROL_SYNC_ENABLED:'true',ENFORCEMENT_READY:'true',NOTIFICATIONS_ENABLED:'true'});
const request=(path,body)=>new Request('https://ops.test'+path,body?{method:'POST',headers:{Origin:'https://ops.test','Content-Type':'application/json'},body:JSON.stringify(body)}:{});
function fakeFetch(log,failControl=false){return async(url,options={})=>{
 log.push({url,body:options.body?JSON.parse(options.body):null});
 if(url.includes('/channels/')&&url.endsWith('/messages'))return Response.json({id:'222222222222222222'});
 if(url.includes('/users/@me/channels'))return Response.json({id:'333333333333333333'});
 if(url.endsWith('/graphql'))return Response.json({data:{viewer:{accounts:[{workersInvocationsAdaptive:[{sum:{requests:1}}],r2OperationsAdaptiveGroups:[]}]}}});
 const body=JSON.parse(options.body);
 if(body.action==='control'&&failControl&&url.includes('ranking.'))return new Response('',{status:402});
 if(body.action==='snapshot')return Response.json({databaseBytes:100,tables:[],storage:[]});
 if(body.action==='references')return Response.json({keys:[],checkedAt:new Date(stamp).toISOString(),ledgerBytes:0,ledgerCount:0});
 return Response.json({ok:true});
};}
const options=more=>({verify:async()=>true,now:()=>stamp,pause:async()=>{},...more});
test('no Access identity: no data/asset read and no write',async()=>{const env=baseEnv();const worker=createOpsWorker(options({verify:async()=>false,fetchImpl:async()=>{throw Error('network');}}));for(const path of ['/','/dashboard.js','/api/latest','/api/history'])assert.equal((await worker.fetch(request(path),env,{})).status,403);assert.equal(env.OPS_DATA.gets,0);});
test('latest/history are snapshot reads only; no refresh of production',async()=>{const env=baseEnv();await env.OPS_DATA.put('state.json',JSON.stringify(healthy()));const worker=createOpsWorker(options({fetchImpl:async()=>{throw Error('no production fetch allowed');}}));assert.equal((await worker.fetch(request('/api/latest'),env,{})).status,200);assert.equal((await worker.fetch(request('/api/history'),env,{})).status,200);assert.equal((await worker.fetch(request('/api/delete',{confirm:true}),env,{})).status,404);});
test('writes require same origin and manual entry updates freshness immediately',async()=>{const env=baseEnv();const state=healthy();state.raw.egress.failures=2;await env.OPS_DATA.put('state.json',JSON.stringify(state));const worker=createOpsWorker(options());const cross=request('/api/egress',egress);cross.headers.set('Origin','https://evil.test');assert.equal((await worker.fetch(cross,env,{})).status,403);assert.equal((await worker.fetch(request('/api/egress',egress),env,{})).status,200);const saved=await (await env.OPS_DATA.get('state.json')).json();assert.equal(saved.raw.egress.failures,0);});
test('partial resume failure does not report success and re-latches both DBs',async()=>{const env=baseEnv(),state=healthy(),log=[];state.blocked=true;await env.OPS_DATA.put('state.json',JSON.stringify(state));const worker=createOpsWorker(options({fetchImpl:fakeFetch(log,true)}));assert.equal((await worker.fetch(request('/api/resume',{confirm:true}),env,{})).status,409);assert.equal((await (await env.OPS_DATA.get('state.json')).json()).blocked,true);assert.ok(log.some(x=>x.url.includes('main.')&&x.body?.value?.blocked));});
test('safe owner resume explicitly clears latch',async()=>{const env=baseEnv(),state=healthy(),log=[];state.blocked=true;await env.OPS_DATA.put('state.json',JSON.stringify(state));const worker=createOpsWorker(options({fetchImpl:fakeFetch(log)}));assert.equal((await worker.fetch(request('/api/resume',{confirm:true}),env,{})).status,200);assert.equal((await (await env.OPS_DATA.get('state.json')).json()).blocked,false);assert.equal(log.filter(x=>x.body?.action==='control').length,2);});
test('hourly collection, duplicate suppression, DM24h and 2 failures',async()=>{let time=stamp;const env=baseEnv(),state=healthy(),log=[];state.raw.minkiru.value.storage=[{bucket:'naga-question-assets',bytes:780e6,count:2,unknown:0}];state.raw.ranking.failures=2;await env.OPS_DATA.put('state.json',JSON.stringify(state));const worker=createOpsWorker(options({now:()=>time,fetchImpl:fakeFetch(log)}));await worker.tick(env);const first=log.filter(x=>x.url.endsWith('/messages')).length;assert.equal(first,2);await worker.tick(env);assert.equal(log.filter(x=>x.url.endsWith('/messages')).length,first);time+=15*60000;await worker.tick(env);assert.equal(log.filter(x=>x.url.endsWith('/messages')).length,first,'same alerts not sent again');assert.equal(log.filter(x=>x.body?.action==='snapshot').length,0,'DB metadata is not queried on each15minute tick');});
test('24 hours alone cannot arm; 96 successful observations are also needed',()=>{const state=healthy();state.enforcementApproved=false;state.raw.minkiru.value.databaseBytes=490e6;assert.equal(snapshot(state,stamp).control.mode,'observe');state.enforcementApproved=true;assert.equal(snapshot(state,stamp).control.mode,'blocked');});
test('inventory uses only R2 metadata, includes management and retains unknown',async()=>{const env=baseEnv(),log=[];await env.IMAGES.put('naga-question-assets/old.png','123');await env.IMAGES.put('unknown/x','12');await env.OPS_DATA.put('state.json','{}');env.IMAGES.get=()=>{throw Error('image body must not be downloaded');};const result=await inventory(env,fakeFetch(log));assert.equal(result.bytes,7);assert.equal(result.oldCount,1);assert.equal(result.unknownCount,1);assert.equal(result.managementBytes,2);});
test('retention deletes only expired generated management history',async()=>{const bucket=new Bucket();for(const key of ['recent/2026-08-01T00:00:00.000Z.json','daily/2026-01-01.json','state.json','images/preserved.png','recent/custom.json']){await bucket.put(key,'{}');bucket.rows.get(key).uploaded=new Date(stamp-100*DAY);}await pruneSnapshots(bucket,stamp);assert.deepEqual(bucket.deletes.sort(),['daily/2026-01-01.json','recent/2026-08-01T00:00:00.000Z.json']);});
